### ISSUE TITLE
Accuracy error unstable

### ISSUE THREAD

**Issue by amarpazad** [fungtion/DANN#2]
Hi, 
I ran the code and  found results
epoch: 98, [iter: 461 / all 461], err_s_label: 0.039522, err_s_domain: 0.636988, err_t_domain: 0.617111
epoch: 98, accuracy of the mnist dataset: 0.989100
epoch: 98, accuracy of the mnist_m dataset: 0.893790
This is even more than the paper where author's have quoted ~ 0.76 over mnist_m. What could be the issue ? Would be great if you can share accuracy you obtained on this code ?
Any version issue ? Would be great if you can share the versions of packages (py,torch, etc.). Maybe the environment.yml file itself.

**Comment by fungtion** [comment]
@amarpazad what's the difference between the implementation of the paper and mine are as follows:
1. I use ADAM instead of SGD
2. I only multiply with \lambda in the back propagation of the feature extractor, rather than all the layer
I don't know if any other differences, you can check the above two points.

**Comment by amarpazad** [comment]
@fungtion These points seem fine. However, we should expect target accuracy around 76% and we get around 89%. I ran the code several times.  What accuracy you obtained on target mnist_m data. Any idea why? Any suggestions?
