### ISSUE TITLE
Question about ReverseLayerF

### ISSUE THREAD

**Issue by SongweiGe** [fungtion/DANN#3]
Greetings! Could you give me some quick explanation about why ReverseLayerF() could lead the gradients of parameters in domain classifier to negative? I'm confused since that I though it would instead influence the parameters before domain classifier (in the feature layer). Could you please correct me a little bit? Thanks in advance!

**Comment by fungtion** [comment]
ReverseLayerF() actually doesn't affect the parameters in domain classifier, since when forward propagation, it equals to 1 https://github.com/fungtion/DANN/blob/master/models/functions.py#L10
and when backward propagation, it only make the gradients from domain classifier  to feature layer negative, i.e. only affect the parameters before domain classifier as you thought .

**Comment by SongweiGe** [comment]
Thx, it makes sense!

**Comment by SongweiGe** [comment]
BTW, why did you use "x.view_as(x)" as return? Is it a convention or a double check?

**Comment by fungtion** [comment]
It is necessary, if you return x which is also the input of forward(), backward() will not be recalled.

**Comment by SongweiGe** [comment]
I see. Thx!

**Comment by houchenyu** [comment]
Greeting! I have a question about ReverseLayerF.apply() in the model definition. There is no explicit definition of the apply() function. What would happen while executing `ReverseLayerF.apply()`

**Comment by SamuelWong77** [comment]
> Greeting! I have a question about ReverseLayerF.apply() in the model definition. There is no explicit definition of the apply() function. What would happen while executing `ReverseLayerF.apply()`


Hi，do u understand how does the  `ReverseLayerF.apply()` work?
